name: Release

on:
  release:
    types: [published]
  workflow_call:

jobs:
  publish_pkg:
    if: ${{ (github.event_name == 'release' && github.event.action == 'published') }}

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Cache dev-js environment
        uses: actions/cache@v3
        with:
          path: node_modules
          key: cache_dev_js_ubuntu22_${{ hashFiles('package-lock.json') }}

      - name: Get workflow ID
        id: workflow_id
        run: |
          workflow_data=$(curl -s -X GET \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.VIZZUHQ_GITHUB_API }}" \
            "https://api.github.com/repos/$GITHUB_REPOSITORY/actions/workflows")
          workflow_id=$(echo $workflow_data | jq -r '.workflows[] | select(.name == "CI-CD") | .id')
          echo "workflow_id=${workflow_id}" >> $GITHUB_OUTPUT

      - name: Get run ID
        id: run_id
        run: |
          run_data=$(curl -s -X GET \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.VIZZUHQ_GITHUB_API }}" \
            "https://api.github.com/repos/$GITHUB_REPOSITORY/actions/workflows/${{ steps.workflow_id.outputs.workflow_id }}/runs?branch=main")
          run_id=$(echo $run_data | jq -r '.workflow_runs[0].id')
          echo "run_id=${run_id}" >> $GITHUB_OUTPUT

      - name: Cache package
        uses: actions/cache@v3
        with:
          path: |
            README.md
            build/
          key: cache_package_${{ steps.run_id.outputs.run_id }}

      - name: Release package
        run: |
          npm config set registry=https://registry.npmjs.org/
          npm config set //registry.npmjs.org/:_authToken=${NPM_API_TOKEN}
          npm publish
        env:
          NPM_API_TOKEN: ${{ secrets.NPM_API_TOKEN }}

      - name: Upload package
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
          gh release upload ${{ github.event.release.tag_name }} build/*tgz --clobber
